jQuery(document).ready(function(){function isInt(value){return(parseFloat(value)==parseInt(value))&&!isNaN(value)}
jQuery('#pointandgrade').prop('selected',!1).find('option:first').prop('selected',!0);jQuery('#button').click(function(){var get_object={};jQuery("#calculate-form #subject_all").each(function(){var length_all=jQuery(this).attr("name").length;var val_all=jQuery(this).val();var Name=jQuery(this).attr("name");if(length_all>0){if(val_all==''){get_object=''}else{var value=jQuery(this).val();get_object[Name]=value}}});var keys=Object.keys(get_object);var duplicate=!1;for(var i=0;i<keys.length;i++){for(var j=i+1;j<keys.length;j++){if(get_object[keys[i]]===get_object[keys[j]]){duplicate=!0;break}}
if(duplicate){alert('Warning: Duplicate Subject Issue Detected!');break}}
if(duplicate!==!0){var fieldPair={};jQuery("#calculate-form #pointandgrade").each(function(){var length=jQuery(this).attr("name").length;var val=jQuery(this).val();var fieldName=jQuery(this).attr("name");if(length>0){if(val==''){fieldPair=''}else{var form_value=jQuery(this).val();fieldPair[fieldName]=form_value}}});if(fieldPair==''){alert('Warning: Some Point or Grade Field Are Empty! ')}else{var bangla,english,information,subject_1,subject_2,subject_3,subject_4='';var bangla_value=fieldPair.bangla
if(isInt(bangla_value)){if(bangla_value==0){bangla=0}else{bangla=parseInt(bangla_value)}}else{bangla=parseFloat(bangla_value)}
var english_value=fieldPair.english
if(isInt(english_value)){if(english_value==0){english=0}else{english=parseInt(english_value)}}else{english=parseFloat(english_value)}
var information_value=fieldPair.information
if(isInt(information_value)){if(information_value==0){information=0}else{information=parseInt(information_value)}}else{information=parseFloat(information_value)}
var subject_1_value=fieldPair.group_sub_1
if(isInt(subject_1_value)){if(subject_1_value==0){subject_1=0}else{subject_1=parseInt(subject_1_value)}}else{subject_1=parseFloat(subject_1_value)}
var subject_2_value=fieldPair.group_sub_2
if(isInt(subject_2_value)){if(subject_2_value==0){subject_2=0}else{subject_2=parseInt(subject_2_value)}}else{subject_2=parseFloat(subject_2_value)}
var subject_3_value=fieldPair.group_sub_3
if(isInt(subject_3_value)){if(subject_3_value==0){subject_3=''}else{subject_3=parseInt(subject_3_value)}}else{subject_3=parseFloat(subject_3_value)}
var subject_4_value=fieldPair.group_sub_4
if(isInt(subject_4_value)){if(subject_4_value==0){subject_4=0}else{subject_4=parseInt(subject_4_value)}}else{subject_4=parseFloat(subject_4_value)}
var sum=(bangla+english+information+subject_1+subject_2+subject_3);var optional=(subject_4-2);var total=(sum+optional);var result=(total/6);var result=result.toFixed(2);if(result>=5){var final=5}else{if(result==3.75){var final='3.50'}else{var final=result}}
var points='';if(bangla<1){points='F';var message='danger_result'}else if(english<1){points='F';var message='danger_result'}else if(information<1){points='F';var message='danger_result'}else if(subject_1<1){points='F';var message='danger_result'}else if(subject_2<1){points='F';var message='danger_result'}else if(subject_3<1){points='F';var message='danger_result'}else{if(result>=5){points='A+';var message='success_result'}else if(result>=4){points='A';var message='success_result'}else if(result>=3.5){points='A-';var message='primary_result'}else if(result>=3){points='B';var message='primary_result'}else if(result>=2){points='C';var message='primary_result'}else if(result>=1){points='D';var message='primary_result'}}
jQuery(".result").html(' <div class="total_result">\n'+'                <div class="total_grade '+message+'">\n'+'                    <div class="total">\n'+'                        <p class="title">Your Grade</p>\n'+'                        <p class="grade">'+points+'</p>\n'+'                    </div>\n'+'                </div>\n'+'                <div class="total_point '+message+'">\n'+'                    <div class="total">\n'+'                        <p class="title">Your Point</p>\n'+'                        <p class="point">'+final+'</p>\n'+'                    </div>\n'+'                </div>\n'+'            </div>')}}})})
